tap "golangci/tap"
tap "sv-tools/apps"
tap "goreleaser/tap"

# Fast linters runner for Go.
brew "golangci/tap/golangci-lint"
# bumptag is a tool to increment a version and to create a git tag with an annotation.
brew "sv-tools/apps/bumptag"
# Deliver Go binaries as fast and easily as possible
brew "goreleaser/tap/goreleaser"
