tap "golangci/tap"
tap "vektra/tap"
tap "kyoh86/tap"
tap "sv-tools/apps"
tap "goreleaser/tap"

# Fast linters runner for Go.
brew "golangci/tap/golangci-lint"
# Rich-Go will enrich `go test` outputs with text decorations
brew "kyoh86/tap/richgo"
# bumptag is a tool to increment a version and to create a git tag with an annotation.
brew "sv-tools/apps/bumptag"
# A mock code autogenerator for Go
brew "vektra/tap/mockery"
# Deliver Go binaries as fast and easily as possible
brew "goreleaser/tap/goreleaser"
