version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      golangci-lint:
        patterns:
          - "golangci*"
      ci:
        patterns:
          - "*"
