version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: ".github/tools/"
    schedule:
      interval: weekly
    groups:
      ci-tools:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      ci:
        patterns:
          - "*"
