version: "2"

linters:
  default: none

  enable: # keep in ascending order
    - asasalint
    - asciicheck
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - recvcheck
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    misspell:
      locale: US
    nestif:
      min-complexity: 12
    goconst:
      min-len: 3
      min-occurrences: 3
    prealloc:
      for-loops: true
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint

  exclusions:
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - gosec

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sv-tools/openapi)
    gofumpt:
      extra-rules: true
