name: Code

on:
  push:
    tags:
      - v*
    branches:
      - main
      - v*
  pull_request:
  schedule:
    - cron: '38 5 * * 3'

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
  cancel-in-progress: true

permissions: read-all

jobs:
  UnitTestJob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ matrix.go }}
      - name: gofmt
        run: diff -u <(echo -n) <(gofmt -l . )
      - name: show diff
        if: ${{ failure() }}
        run: git diff
      - name: go vet
        run: go vet ./...
      - name: Run Unit Tests
        run: go test -race -cover -coverprofile=coverage.out -covermode=atomic ./...
      - name: Codecov
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5.1.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  UnitTests:
    if: ${{ always() }}
    needs: UnitTestJob
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        if: ${{ needs.UnitTestJob.result != 'success' }}
        run: exit 1
